version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  mongo:
    image: mongo
    ports:
      - 27017:27017
    depends_on:
      - rabbitmq
    volumes:
      - mongodb:/data/db
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:27017"]
        interval: 30s
        timeout: 10s
        retries: 5

  gateway-qql-example:
    build: ./Services/Gateway
    ports: 
      - "5000:5000"
    depends_on:
      - mongo
      - rabbitmq
      - ms-qql-service-a
      - ms-qql-service-b
    environment:
      - NODE_ENV=debug
      - SERVICE_URL=ms-qql
    deploy:
      restart_policy: 
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  ms-qql-service-a:
    build: ./Services/serviceA
    ports: 
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=debug
    deploy:
      restart_policy: 
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  ms-qql-service-b:
      build: ./Services/serviceB
      ports: 
        - "5002:5002"
      depends_on:
        - mongo
      environment:
        - NODE_ENV=debug      
      deploy:
        restart_policy: 
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s

volumes:
  mongodb:

